# Generated by Django 4.2 on 2023-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
    ]
