# Generated by Django 4.2 on 2023-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('projects', '0002_rename_created_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='skills.skill'),
        ),
    ]
