# Generated by Django 4.2 on 2023-04-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_remove_developer_projects_remove_developer_skills'),
        ('projects', '0003_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='developers.developer'),
            preserve_default=False,
        ),
    ]
