# Generated by Django 4.2 on 2023-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_created_at_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
