# Generated by Django 4.2 on 2023-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_project_name_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
