# Generated by Django 4.2 on 2023-04-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='projects',
            new_name='project',
        ),
    ]
