# Generated by Django 4.2 on 2023-04-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_created_project_created_at_and_more'),
        ('comments', '0003_remove_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project'),
            preserve_default=False,
        ),
    ]
