# Generated by Django 4.2 on 2023-04-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skills',
        ),
    ]
