# Generated by Django 4.2 on 2023-04-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skills',
        ),
        migrations.AddField(
            model_name='developer',
            name='project_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='skills.skill'),
            preserve_default=False,
        ),
    ]
