# Generated by Django 4.2 on 2023-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
        ('developers', '0003_remove_developer_project_url_remove_developer_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project_url',
            field=models.ManyToManyField(blank=True, related_name='developers', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='developers', to='skills.skill'),
        ),
    ]
