# Generated by Django 4.2 on 2023-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
        ('developers', '0004_alter_developer_project_url_alter_developer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project_url',
            field=models.ManyToManyField(related_name='developers', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(related_name='developers', to='skills.skill'),
        ),
    ]
