# Generated by Django 4.2 on 2023-04-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0011_rename_skills_developer_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project_url',
        ),
    ]
