# Generated by Django 4.2 on 2023-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('developers', '0014_remove_developer_based_in_remove_developer_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='img',
        ),
        migrations.AddField(
            model_name='developer',
            name='skill',
            field=models.ManyToManyField(related_name='developers', to='skills.skill'),
        ),
    ]
