# Generated by Django 4.2 on 2023-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0015_remove_developer_img_developer_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
        migrations.AddField(
            model_name='developer',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
