# Generated by Django 4.2 on 2023-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('developers', '0016_remove_developer_skill_developer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='title',
        ),
        migrations.AddField(
            model_name='developer',
            name='skill',
            field=models.ManyToManyField(related_name='developers', to='skills.skill'),
        ),
    ]
