# Generated by Django 4.2 on 2023-04-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0020_remove_developer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
    ]
