# Generated by Django 4.2 on 2023-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description'),
        ('skills', '0001_initial'),
        ('developers', '0021_remove_developer_project_url_remove_developer_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='project_url',
            field=models.ManyToManyField(related_name='developers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='developer',
            name='skill',
            field=models.ManyToManyField(related_name='developers', to='skills.skill'),
        ),
    ]
