# Generated by Django 4.2 on 2023-04-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0026_developer_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
    ]
