# Generated by Django 4.2 on 2023-04-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0029_developer_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
    ]
