# Generated by Django 4.2 on 2023-05-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0032_developer_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project_url',
        ),
    ]
