# Generated by Django 4.2 on 2023-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description'),
        ('developers', '0033_remove_developer_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(related_name='developers', to='projects.project'),
        ),
    ]
