# Generated by Django 4.2 on 2023-05-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0034_developer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
    ]
