# Generated by Django 4.2 on 2023-05-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_title_project_project_name'),
        ('developers', '0035_remove_developer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(related_name='developers', to='projects.project'),
        ),
    ]
