# Generated by Django 4.2 on 2023-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0036_developer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='info',
            field=models.TextField(max_length=5000),
        ),
    ]
