# Generated by Django 4.2 on 2023-05-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0038_remove_developer_project_remove_developer_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='owner',
        ),
    ]
