# Generated by Django 4.2 on 2023-05-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0040_developer_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
    ]
