# Generated by Django 4.2 on 2023-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description'),
        ('developers', '0042_developer_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(related_name='developers', to='projects.project'),
        ),
    ]
